version: '3'
services:
  gg2rdf:
    image: tmp/gg2rdf
    build:
      context: ..
      dockerfile: Dockerfile
    command: /bin/sh -c "cp -r /root/.ssh-host /root/.ssh; chmod -R 0700 /root/.ssh; cat /root/.gitconfig-host > /root/.gitconfig; while sleep 1000; do :; done"
    volumes:
      - ../:/workspaces/gg2rdf
      - gg2rdf_data:/workdir
      - ~/.gitconfig:/root/.gitconfig-host
      - ~/.ssh:/root/.ssh-host:ro
    env_file:
     - ../.env
volumes:
  gg2rdf_data:
    driver: local