version: '3'
services:
  ghact:
    image: tmp/ghact
    build:
      context: ..
      dockerfile: Dockerfile
    command: /bin/sh -c "cp -r /root/.ssh-host /root/.ssh; chmod -R 0700 /root/.ssh; cat /root/.gitconfig-host > /root/.gitconfig; while sleep 1000; do :; done"
    volumes:
      - ../:/workspaces/ghact
      - ghact_data:/workdir
      - ~/.gitconfig:/root/.gitconfig-host
      - ~/.ssh:/root/.ssh-host:ro
    # env_file:
    # - ../.env
volumes:
  ghact_data:
    driver: local